"""
Django settings for levis project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'x*$u#j0yztvu-$83zh=-7mo4eg5o%cm9!3krs)9q=&=1tni@zk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
                 'https://met-data-approval.cartesianconsulting.com',
                 'met-app-backend.cartesianconsulting.com',
                 '52.220.172.9',
                 '10.0.0.71',
                 ]

# ALLOWED_HOSTS = ['*']

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'corsheaders',
    'rest_framework',
    'upload'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'levis.urls'

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ('https://met-data-approval.cartesianconsulting.com','https://10.0.0.71')
CORS_ALLOW_HEADERS = ('X-Requested-With','X-HTTP-Method_Override','Content-Type','Accept','Authorization')

CORS_ALLOW_METHODS = ('DELETE','GET','OPTIONS','PATCH','POST','PUT',)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
        'rest_framework.permissions.AllowAny',
    )
}

OAUTH2_PROVIDER = {
    # this is the list of available scopes
    'SCOPES': {'read': 'Read scope', 'write': 'Write scope', 'groups': 'Access to your groups'},
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'transworld.wsgi.application'
WSGI_APPLICATION = 'levis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'LEVIS_MET2',#'LEVIS_TEST',
        'USER': 'rahul',
        'PASSWORD': 'Cart@123', 
        'HOST':'10.0.0.71',
        'PORT':3306
    },
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,'static/')


# OAUTH_CLIENT_ID = "WNXplF4lVkhsELmjHRsdicv0pAdt0n9DjqFAMJdT"
# OAUTH_CLIENT_SECRET = "zvqctF8giNKKSpNb7WzZGzf6nonBFg3opcBYZAO6JbGsBOitaKh6kTGfbjEpbl2T5ZkJs7KP8Re0c9OZo4x41H3pNChsTN3lE5nDTVgGMmUlZxsQoK9my1ZNizNMQOLd"

OAUTH_CLIENT_ID = "4xy6pN3S9W83XecaAK4ZFk3UKjtkxtM34LEE1f03"
OAUTH_CLIENT_SECRET = "LUTTtFGDxDN2qAfRgaNZVcYEq6Pu5K6NDLxUQcp3Ft1xQ43u8cPr5jCkHOvUdBXQeJlyT6QvZXFXTrtwAn7Pwh8HjBZ3pvC5LDdJQWFXLx6cvm23DROvTBj6RvhSirIY"

# OAUTH_CLIENT_ID = "vjRnrqoBDMHSMI6JMDJPMZ9ZhubO3a2QEbmnkxjX"
# OAUTH_CLIENT_SECRET = "8JrF8YQb4Niac8zxfcptL5503PaE4FzIb3YNJC7ZdHJD8KUOUk7X0ltN4xPcj3DQAyBWxkZkH3S1SDqr3VVcx3obvjsMWtBZ32SUVDcfwY3aBJLb8tVHT6qSS9LL8Uv9"

BASE_URL = "http://52.220.172.9:9002/"

# BASE_URL = "met-app-backend.cartesianconsulting.com:9002"


# BASE_URL = "http://10.0.0.71:8000/"

SESSION_EXPIRE_SECONDS = 60
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True


BROKER_URL =  'redis://127.0.0.1:6379'
# BROKER_URL =  'redis://10.0.0.71:6379' #'redis://127.0.0.1:6379'
# BROKER_URL =  'redis://52.220.172.9:6379' #'redis://127.0.0.1:6379'
# CELERY_RESULT_BACKEND = 'redis://52.220.172.9:6379' #'redis://127.0.0.1:6379'
# CELERY_RESULT_BACKEND = 'redis://10.0.0.71:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
