create
    definer = gilbert@`%` procedure Pop_Fact_DB_Social_China(IN i_Job_ID int)
BEGIN
    SET SQL_SAFE_UPDATES = 0;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 0, CURRENT_TIMESTAMP());

    TRUNCATE TABLE Stg_Fact_DB_Social_China;

    INSERT INTO Stg_Fact_DB_Social_China (Year_Month_Num, Fiscal_Quarter, Fiscal_Year, Fiscal_Month, Country, Region)
    SELECT DISTINCT Year_Month_Num, Fiscal_Quarter, Fiscal_Year, Fiscal_Month, Country, Region
    FROM Dim_Calendar_Month,
         Dim_Country
    WHERE Year_Month_Num <= DATE_FORMAT(DATE_ADD(NOW(), INTERVAL -1 MONTH), '%Y%m')
    ORDER BY Year_Month_Num;

    COMMIT;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 10, CURRENT_TIMESTAMP());

    UPDATE Stg_Fact_DB_Social_China SF, SocialMedia_China SMC
    SET SF.Social_Month                          = SMC.Social_Month,
        SF.Weibo_Followers_Uniqlo                = SMC.Weibo_Followers_Uniqlo,
        SF.Weibo_Followers_HM                    = SMC.Weibo_Followers_HM,
        SF.Weibo_Followers_Zara                  = SMC.Weibo_Followers_Zara,
        SF.Weibo_Followers_Levis                 = SMC.Weibo_Followers_Levis,
        SF.Weibo_Followers_Lee                   = SMC.Weibo_Followers_Lee,
        SF.Weibo_Followers_Gap                   = SMC.Weibo_Followers_Gap,
        SF.Weibo_Tweet_Uniqlo                    = SMC.Weibo_Tweet_Uniqlo,
        SF.Weibo_Tweet_HM                        = SMC.Weibo_Tweet_HM,
        SF.Weibo_Tweet_Zara                      = SMC.Weibo_Tweet_Zara,
        SF.Weibo_Tweet_Levis                     = SMC.Weibo_Tweet_Levis,
        SF.Weibo_Tweet_Lee                       = SMC.Weibo_Tweet_Lee,
        SF.Weibo_Tweet_Gap                       = SMC.Weibo_Tweet_Gap,
        SF.Weibo_Retweet_Uniqlo                  = SMC.Weibo_Retweet_Uniqlo,
        SF.Weibo_Retweet_HM                      = SMC.Weibo_Retweet_HM,
        SF.Weibo_Retweet_Zara                    = SMC.Weibo_Retweet_Zara,
        SF.Weibo_Retweet_Levis                   = SMC.Weibo_Retweet_Levis,
        SF.Weibo_Retweet_Lee                     = SMC.Weibo_Retweet_Lee,
        SF.Weibo_Retweet_Gap                     = SMC.Weibo_Retweet_Gap,
        SF.Weibo_Comment_Uniqlo                  = SMC.Weibo_Comment_Uniqlo,
        SF.Weibo_Comment_HM                      = SMC.Weibo_Comment_HM,
        SF.Weibo_Comment_Zara                    = SMC.Weibo_Comment_Zara,
        SF.Weibo_Comment_Levis                   = SMC.Weibo_Comment_Levis,
        SF.Weibo_Comment_Lee                     = SMC.Weibo_Comment_Lee,
        SF.Weibo_Comment_Gap                     = SMC.Weibo_Comment_Gap,
        SF.Weibo_Likes_Uniqlo                    = SMC.Weibo_Likes_Uniqlo,
        SF.Weibo_Likes_HM                        = SMC.Weibo_Likes_HM,
        SF.Weibo_Likes_Zara                      = SMC.Weibo_Likes_Zara,
        SF.Weibo_Likes_Levis                     = SMC.Weibo_Likes_Levis,
        SF.Weibo_Likes_Lee                       = SMC.Weibo_Likes_Lee,
        SF.Weibo_Likes_Gap                       = SMC.Weibo_Likes_Gap,
        SF.Weibo_Buzz_Uniqlo                     = SMC.Weibo_Buzz_Uniqlo,
        SF.Weibo_Buzz_HM                         = SMC.Weibo_Buzz_HM,
        SF.Weibo_Buzz_Zara                       = SMC.Weibo_Buzz_Zara,
        SF.Weibo_Buzz_Levis                      = SMC.Weibo_Buzz_Levis,
        SF.Weibo_Buzz_Lee                        = SMC.Weibo_Buzz_Lee,
        SF.Weibo_Buzz_Gap                        = SMC.Weibo_Buzz_Gap,
        SF.Weibo_Sentiment_Uniqlo                = SMC.Weibo_Sentiment_Uniqlo,
        SF.Weibo_Sentiment_HM                    = SMC.Weibo_Sentiment_HM,
        SF.Weibo_Sentiment_Zara                  = SMC.Weibo_Sentiment_Zara,
        SF.Weibo_Sentiment_Levis                 = SMC.Weibo_Sentiment_Levis,
        SF.Weibo_Sentiment_Lee                   = SMC.Weibo_Sentiment_Lee,
        SF.Weibo_Sentiment_Gap                   = SMC.Weibo_Sentiment_Gap,
        SF.Wechat_Avg_view_top_3_articles_Uniqlo = SMC.Wechat_Avg_view_top_3_articles_Uniqlo,
        SF.Wechat_Avg_view_top_3_articles_HM     = SMC.Wechat_Avg_view_top_3_articles_HM,
        SF.Wechat_Avg_view_top_3_articles_Zara   = SMC.Wechat_Avg_view_top_3_articles_Zara,
        SF.Wechat_Avg_view_top_3_articles_Levis  = SMC.Wechat_Avg_view_top_3_articles_Levis,
        SF.Wechat_Avg_view_top_3_articles_Lee    = SMC.Wechat_Avg_view_top_3_articles_Lee,
        SF.Wechat_Avg_view_top_3_articles_Gap    = SMC.Wechat_Avg_view_top_3_articles_Gap,
        SF.Wechat_Avg_like_top_3_articles_Uniqlo = SMC.Wechat_Avg_like_top_3_articles_Uniqlo,
        SF.Wechat_Avg_like_top_3_articles_HM     = SMC.Wechat_Avg_like_top_3_articles_HM,
        SF.Wechat_Avg_like_top_3_articles_Zara   = SMC.Wechat_Avg_like_top_3_articles_Zara,
        SF.Wechat_Avg_like_top_3_articles_Levis  = SMC.Wechat_Avg_like_top_3_articles_Levis,
        SF.Wechat_Avg_like_top_3_articles_Lee    = SMC.Wechat_Avg_like_top_3_articles_Lee,
        SF.Wechat_Avg_like_top_3_articles_Gap    = SMC.Wechat_Avg_like_top_3_articles_Gap,
        SF.Weibo_Followers_Growth_Uniqlo         = SMC.Weibo_Followers_Growth_Uniqlo,
        SF.Weibo_Followers_Growth_HM             = SMC.Weibo_Followers_Growth_HM,
        SF.Weibo_Followers_Growth_Zara           = SMC.Weibo_Followers_Growth_Zara,
        SF.Weibo_Followers_Growth_Levis          = SMC.Weibo_Followers_Growth_Levis,
        SF.Weibo_Followers_Growth_Lee            = SMC.Weibo_Followers_Growth_Lee,
        SF.Weibo_Followers_Growth_Gap            = SMC.Weibo_Followers_Growth_Gap,
        SF.Weibo_Engagement_Rate_Uniqlo          = SMC.Weibo_Engagement_Rate_Uniqlo,
        SF.Weibo_Engagement_Rate_HM              = SMC.Weibo_Engagement_Rate_HM,
        SF.Weibo_Engagement_Rate_Zara            = SMC.Weibo_Engagement_Rate_Zara,
        SF.Weibo_Engagement_Rate_Levis           = SMC.Weibo_Engagement_Rate_Levis,
        SF.Weibo_Engagement_Rate_Lee             = SMC.Weibo_Engagement_Rate_Lee,
        SF.Weibo_Engagement_Rate_Gap             = SMC.Weibo_Engagement_Rate_Gap
    WHERE SF.Year_Month_Num = SMC.Year_Month_Num
      AND SF.Country = SMC.Country;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 20, CURRENT_TIMESTAMP());

    UPDATE Stg_Fact_DB_Social_China SF,
        (SELECT CASE
                    WHEN SUBSTR(Year_Month_Num, 5, 2) = '12' THEN Year_Month_Num + 89
                    ELSE Year_Month_Num + 1 END P_Year_Month_Num,
                Country,
                Weibo_Followers_Uniqlo,
                Weibo_Followers_HM,
                Weibo_Followers_Zara,
                Weibo_Followers_Levis,
                Weibo_Followers_Lee,
                Weibo_Followers_Gap,
                Weibo_Tweet_Uniqlo,
                Weibo_Tweet_HM,
                Weibo_Tweet_Zara,
                Weibo_Tweet_Levis,
                Weibo_Tweet_Lee,
                Weibo_Tweet_Gap,
                Weibo_Retweet_Uniqlo,
                Weibo_Retweet_HM,
                Weibo_Retweet_Zara,
                Weibo_Retweet_Levis,
                Weibo_Retweet_Lee,
                Weibo_Retweet_Gap,
                Weibo_Comment_Uniqlo,
                Weibo_Comment_HM,
                Weibo_Comment_Zara,
                Weibo_Comment_Levis,
                Weibo_Comment_Lee,
                Weibo_Comment_Gap,
                Weibo_Likes_Uniqlo,
                Weibo_Likes_HM,
                Weibo_Likes_Zara,
                Weibo_Likes_Levis,
                Weibo_Likes_Lee,
                Weibo_Likes_Gap,
                Weibo_Buzz_Uniqlo,
                Weibo_Buzz_HM,
                Weibo_Buzz_Zara,
                Weibo_Buzz_Levis,
                Weibo_Buzz_Lee,
                Weibo_Buzz_Gap,
                Weibo_Sentiment_Uniqlo,
                Weibo_Sentiment_HM,
                Weibo_Sentiment_Zara,
                Weibo_Sentiment_Levis,
                Weibo_Sentiment_Lee,
                Weibo_Sentiment_Gap,
                Wechat_Avg_view_top_3_articles_Uniqlo,
                Wechat_Avg_view_top_3_articles_HM,
                Wechat_Avg_view_top_3_articles_Zara,
                Wechat_Avg_view_top_3_articles_Levis,
                Wechat_Avg_view_top_3_articles_Lee,
                Wechat_Avg_view_top_3_articles_Gap,
                Wechat_Avg_like_top_3_articles_Uniqlo,
                Wechat_Avg_like_top_3_articles_HM,
                Wechat_Avg_like_top_3_articles_Zara,
                Wechat_Avg_like_top_3_articles_Levis,
                Wechat_Avg_like_top_3_articles_Lee,
                Wechat_Avg_like_top_3_articles_Gap,
                Weibo_Followers_Growth_Uniqlo,
                Weibo_Followers_Growth_HM,
                Weibo_Followers_Growth_Zara,
                Weibo_Followers_Growth_Levis,
                Weibo_Followers_Growth_Lee,
                Weibo_Followers_Growth_Gap,
                Weibo_Engagement_Rate_Uniqlo,
                Weibo_Engagement_Rate_HM,
                Weibo_Engagement_Rate_Zara,
                Weibo_Engagement_Rate_Levis,
                Weibo_Engagement_Rate_Lee,
                Weibo_Engagement_Rate_Gap
         FROM Stg_Fact_DB_Social_China) Q
    SET SF.Prev_Weibo_Followers_Uniqlo                = Q.Weibo_Followers_Uniqlo,
        SF.Prev_Weibo_Followers_HM                    = Q.Weibo_Followers_HM,
        SF.Prev_Weibo_Followers_Zara                  = Q.Weibo_Followers_Zara,
        SF.Prev_Weibo_Followers_Levis                 = Q.Weibo_Followers_Levis,
        SF.Prev_Weibo_Followers_Lee                   = Q.Weibo_Followers_Lee,
        SF.Prev_Weibo_Followers_Gap                   = Q.Weibo_Followers_Gap,
        SF.Prev_Weibo_Tweet_Uniqlo                    = Q.Weibo_Tweet_Uniqlo,
        SF.Prev_Weibo_Tweet_HM                        = Q.Weibo_Tweet_HM,
        SF.Prev_Weibo_Tweet_Zara                      = Q.Weibo_Tweet_Zara,
        SF.Prev_Weibo_Tweet_Levis                     = Q.Weibo_Tweet_Levis,
        SF.Prev_Weibo_Tweet_Lee                       = Q.Weibo_Tweet_Lee,
        SF.Prev_Weibo_Tweet_Gap                       = Q.Weibo_Tweet_Gap,
        SF.Prev_Weibo_Retweet_Uniqlo                  = Q.Weibo_Retweet_Uniqlo,
        SF.Prev_Weibo_Retweet_HM                      = Q.Weibo_Retweet_HM,
        SF.Prev_Weibo_Retweet_Zara                    = Q.Weibo_Retweet_Zara,
        SF.Prev_Weibo_Retweet_Levis                   = Q.Weibo_Retweet_Levis,
        SF.Prev_Weibo_Retweet_Lee                     = Q.Weibo_Retweet_Lee,
        SF.Prev_Weibo_Retweet_Gap                     = Q.Weibo_Retweet_Gap,
        SF.Prev_Weibo_Comment_Uniqlo                  = Q.Weibo_Comment_Uniqlo,
        SF.Prev_Weibo_Comment_HM                      = Q.Weibo_Comment_HM,
        SF.Prev_Weibo_Comment_Zara                    = Q.Weibo_Comment_Zara,
        SF.Prev_Weibo_Comment_Levis                   = Q.Weibo_Comment_Levis,
        SF.Prev_Weibo_Comment_Lee                     = Q.Weibo_Comment_Lee,
        SF.Prev_Weibo_Comment_Gap                     = Q.Weibo_Comment_Gap,
        SF.Prev_Weibo_Likes_Uniqlo                    = Q.Weibo_Likes_Uniqlo,
        SF.Prev_Weibo_Likes_HM                        = Q.Weibo_Likes_HM,
        SF.Prev_Weibo_Likes_Zara                      = Q.Weibo_Likes_Zara,
        SF.Prev_Weibo_Likes_Levis                     = Q.Weibo_Likes_Levis,
        SF.Prev_Weibo_Likes_Lee                       = Q.Weibo_Likes_Lee,
        SF.Prev_Weibo_Likes_Gap                       = Q.Weibo_Likes_Gap,
        SF.Prev_Weibo_Buzz_Uniqlo                     = Q.Weibo_Buzz_Uniqlo,
        SF.Prev_Weibo_Buzz_HM                         = Q.Weibo_Buzz_HM,
        SF.Prev_Weibo_Buzz_Zara                       = Q.Weibo_Buzz_Zara,
        SF.Prev_Weibo_Buzz_Levis                      = Q.Weibo_Buzz_Levis,
        SF.Prev_Weibo_Buzz_Lee                        = Q.Weibo_Buzz_Lee,
        SF.Prev_Weibo_Buzz_Gap                        = Q.Weibo_Buzz_Gap,
        SF.Prev_Weibo_Sentiment_Uniqlo                = Q.Weibo_Sentiment_Uniqlo,
        SF.Prev_Weibo_Sentiment_HM                    = Q.Weibo_Sentiment_HM,
        SF.Prev_Weibo_Sentiment_Zara                  = Q.Weibo_Sentiment_Zara,
        SF.Prev_Weibo_Sentiment_Levis                 = Q.Weibo_Sentiment_Levis,
        SF.Prev_Weibo_Sentiment_Lee                   = Q.Weibo_Sentiment_Lee,
        SF.Prev_Weibo_Sentiment_Gap                   = Q.Weibo_Sentiment_Gap,
        SF.Prev_Wechat_Avg_view_top_3_articles_Uniqlo = Q.Wechat_Avg_view_top_3_articles_Uniqlo,
        SF.Prev_Wechat_Avg_view_top_3_articles_HM     = Q.Wechat_Avg_view_top_3_articles_HM,
        SF.Prev_Wechat_Avg_view_top_3_articles_Zara   = Q.Wechat_Avg_view_top_3_articles_Zara,
        SF.Prev_Wechat_Avg_view_top_3_articles_Levis  = Q.Wechat_Avg_view_top_3_articles_Levis,
        SF.Prev_Wechat_Avg_view_top_3_articles_Lee    = Q.Wechat_Avg_view_top_3_articles_Lee,
        SF.Prev_Wechat_Avg_view_top_3_articles_Gap    = Q.Wechat_Avg_view_top_3_articles_Gap,
        SF.Prev_Wechat_Avg_like_top_3_articles_Uniqlo = Q.Wechat_Avg_like_top_3_articles_Uniqlo,
        SF.Prev_Wechat_Avg_like_top_3_articles_HM     = Q.Wechat_Avg_like_top_3_articles_HM,
        SF.Prev_Wechat_Avg_like_top_3_articles_Zara   = Q.Wechat_Avg_like_top_3_articles_Zara,
        SF.Prev_Wechat_Avg_like_top_3_articles_Levis  = Q.Wechat_Avg_like_top_3_articles_Levis,
        SF.Prev_Wechat_Avg_like_top_3_articles_Lee    = Q.Wechat_Avg_like_top_3_articles_Lee,
        SF.Prev_Wechat_Avg_like_top_3_articles_Gap    = Q.Wechat_Avg_like_top_3_articles_Gap,
        SF.Prev_Weibo_Followers_Growth_Uniqlo         = Q.Weibo_Followers_Growth_Uniqlo,
        SF.Prev_Weibo_Followers_Growth_HM             = Q.Weibo_Followers_Growth_HM,
        SF.Prev_Weibo_Followers_Growth_Zara           = Q.Weibo_Followers_Growth_Zara,
        SF.Prev_Weibo_Followers_Growth_Levis          = Q.Weibo_Followers_Growth_Levis,
        SF.Prev_Weibo_Followers_Growth_Lee            = Q.Weibo_Followers_Growth_Lee,
        SF.Prev_Weibo_Followers_Growth_Gap            = Q.Weibo_Followers_Growth_Gap,
        SF.Prev_Weibo_Engagement_Rate_Uniqlo          = Q.Weibo_Engagement_Rate_Uniqlo,
        SF.Prev_Weibo_Engagement_Rate_HM              = Q.Weibo_Engagement_Rate_HM,
        SF.Prev_Weibo_Engagement_Rate_Zara            = Q.Weibo_Engagement_Rate_Zara,
        SF.Prev_Weibo_Engagement_Rate_Levis           = Q.Weibo_Engagement_Rate_Levis,
        SF.Prev_Weibo_Engagement_Rate_Lee             = Q.Weibo_Engagement_Rate_Lee,
        SF.Prev_Weibo_Engagement_Rate_Gap             = Q.Weibo_Engagement_Rate_Gap
    WHERE SF.Year_Month_Num = Q.P_Year_Month_Num
      AND SF.Country = Q.Country;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 30, CURRENT_TIMESTAMP());

    UPDATE Stg_Fact_DB_Social_China SF,
        (SELECT Year_Month_Num + 100 P_Year_Month_Num,
                Country,
                Weibo_Followers_Uniqlo,
                Weibo_Followers_HM,
                Weibo_Followers_Zara,
                Weibo_Followers_Levis,
                Weibo_Followers_Lee,
                Weibo_Followers_Gap,
                Weibo_Tweet_Uniqlo,
                Weibo_Tweet_HM,
                Weibo_Tweet_Zara,
                Weibo_Tweet_Levis,
                Weibo_Tweet_Lee,
                Weibo_Tweet_Gap,
                Weibo_Retweet_Uniqlo,
                Weibo_Retweet_HM,
                Weibo_Retweet_Zara,
                Weibo_Retweet_Levis,
                Weibo_Retweet_Lee,
                Weibo_Retweet_Gap,
                Weibo_Comment_Uniqlo,
                Weibo_Comment_HM,
                Weibo_Comment_Zara,
                Weibo_Comment_Levis,
                Weibo_Comment_Lee,
                Weibo_Comment_Gap,
                Weibo_Likes_Uniqlo,
                Weibo_Likes_HM,
                Weibo_Likes_Zara,
                Weibo_Likes_Levis,
                Weibo_Likes_Lee,
                Weibo_Likes_Gap,
                Weibo_Buzz_Uniqlo,
                Weibo_Buzz_HM,
                Weibo_Buzz_Zara,
                Weibo_Buzz_Levis,
                Weibo_Buzz_Lee,
                Weibo_Buzz_Gap,
                Weibo_Sentiment_Uniqlo,
                Weibo_Sentiment_HM,
                Weibo_Sentiment_Zara,
                Weibo_Sentiment_Levis,
                Weibo_Sentiment_Lee,
                Weibo_Sentiment_Gap,
                Wechat_Avg_view_top_3_articles_Uniqlo,
                Wechat_Avg_view_top_3_articles_HM,
                Wechat_Avg_view_top_3_articles_Zara,
                Wechat_Avg_view_top_3_articles_Levis,
                Wechat_Avg_view_top_3_articles_Lee,
                Wechat_Avg_view_top_3_articles_Gap,
                Wechat_Avg_like_top_3_articles_Uniqlo,
                Wechat_Avg_like_top_3_articles_HM,
                Wechat_Avg_like_top_3_articles_Zara,
                Wechat_Avg_like_top_3_articles_Levis,
                Wechat_Avg_like_top_3_articles_Lee,
                Wechat_Avg_like_top_3_articles_Gap,
                Weibo_Followers_Growth_Uniqlo,
                Weibo_Followers_Growth_HM,
                Weibo_Followers_Growth_Zara,
                Weibo_Followers_Growth_Levis,
                Weibo_Followers_Growth_Lee,
                Weibo_Followers_Growth_Gap,
                Weibo_Engagement_Rate_Uniqlo,
                Weibo_Engagement_Rate_HM,
                Weibo_Engagement_Rate_Zara,
                Weibo_Engagement_Rate_Levis,
                Weibo_Engagement_Rate_Lee,
                Weibo_Engagement_Rate_Gap
         from Stg_Fact_DB_Social_China) Q
    SET SF.Prev_Year_Weibo_Followers_Uniqlo                = Q.Weibo_Followers_Uniqlo,
        SF.Prev_Year_Weibo_Followers_HM                    = Q.Weibo_Followers_HM,
        SF.Prev_Year_Weibo_Followers_Zara                  = Q.Weibo_Followers_Zara,
        SF.Prev_Year_Weibo_Followers_Levis                 = Q.Weibo_Followers_Levis,
        SF.Prev_Year_Weibo_Followers_Lee                   = Q.Weibo_Followers_Lee,
        SF.Prev_Year_Weibo_Followers_Gap                   = Q.Weibo_Followers_Gap,
        SF.Prev_Year_Weibo_Tweet_Uniqlo                    = Q.Weibo_Tweet_Uniqlo,
        SF.Prev_Year_Weibo_Tweet_HM                        = Q.Weibo_Tweet_HM,
        SF.Prev_Year_Weibo_Tweet_Zara                      = Q.Weibo_Tweet_Zara,
        SF.Prev_Year_Weibo_Tweet_Levis                     = Q.Weibo_Tweet_Levis,
        SF.Prev_Year_Weibo_Tweet_Lee                       = Q.Weibo_Tweet_Lee,
        SF.Prev_Year_Weibo_Tweet_Gap                       = Q.Weibo_Tweet_Gap,
        SF.Prev_Year_Weibo_Retweet_Uniqlo                  = Q.Weibo_Retweet_Uniqlo,
        SF.Prev_Year_Weibo_Retweet_HM                      = Q.Weibo_Retweet_HM,
        SF.Prev_Year_Weibo_Retweet_Zara                    = Q.Weibo_Retweet_Zara,
        SF.Prev_Year_Weibo_Retweet_Levis                   = Q.Weibo_Retweet_Levis,
        SF.Prev_Year_Weibo_Retweet_Lee                     = Q.Weibo_Retweet_Lee,
        SF.Prev_Year_Weibo_Retweet_Gap                     = Q.Weibo_Retweet_Gap,
        SF.Prev_Year_Weibo_Comment_Uniqlo                  = Q.Weibo_Comment_Uniqlo,
        SF.Prev_Year_Weibo_Comment_HM                      = Q.Weibo_Comment_HM,
        SF.Prev_Year_Weibo_Comment_Zara                    = Q.Weibo_Comment_Zara,
        SF.Prev_Year_Weibo_Comment_Levis                   = Q.Weibo_Comment_Levis,
        SF.Prev_Year_Weibo_Comment_Lee                     = Q.Weibo_Comment_Lee,
        SF.Prev_Year_Weibo_Comment_Gap                     = Q.Weibo_Comment_Gap,
        SF.Prev_Year_Weibo_Likes_Uniqlo                    = Q.Weibo_Likes_Uniqlo,
        SF.Prev_Year_Weibo_Likes_HM                        = Q.Weibo_Likes_HM,
        SF.Prev_Year_Weibo_Likes_Zara                      = Q.Weibo_Likes_Zara,
        SF.Prev_Year_Weibo_Likes_Levis                     = Q.Weibo_Likes_Levis,
        SF.Prev_Year_Weibo_Likes_Lee                       = Q.Weibo_Likes_Lee,
        SF.Prev_Year_Weibo_Likes_Gap                       = Q.Weibo_Likes_Gap,
        SF.Prev_Year_Weibo_Buzz_Uniqlo                     = Q.Weibo_Buzz_Uniqlo,
        SF.Prev_Year_Weibo_Buzz_HM                         = Q.Weibo_Buzz_HM,
        SF.Prev_Year_Weibo_Buzz_Zara                       = Q.Weibo_Buzz_Zara,
        SF.Prev_Year_Weibo_Buzz_Levis                      = Q.Weibo_Buzz_Levis,
        SF.Prev_Year_Weibo_Buzz_Lee                        = Q.Weibo_Buzz_Lee,
        SF.Prev_Year_Weibo_Buzz_Gap                        = Q.Weibo_Buzz_Gap,
        SF.Prev_Year_Weibo_Sentiment_Uniqlo                = Q.Weibo_Sentiment_Uniqlo,
        SF.Prev_Year_Weibo_Sentiment_HM                    = Q.Weibo_Sentiment_HM,
        SF.Prev_Year_Weibo_Sentiment_Zara                  = Q.Weibo_Sentiment_Zara,
        SF.Prev_Year_Weibo_Sentiment_Levis                 = Q.Weibo_Sentiment_Levis,
        SF.Prev_Year_Weibo_Sentiment_Lee                   = Q.Weibo_Sentiment_Lee,
        SF.Prev_Year_Weibo_Sentiment_Gap                   = Q.Weibo_Sentiment_Gap,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_Uniqlo = Q.Wechat_Avg_view_top_3_articles_Uniqlo,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_HM     = Q.Wechat_Avg_view_top_3_articles_HM,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_Zara   = Q.Wechat_Avg_view_top_3_articles_Zara,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_Levis  = Q.Wechat_Avg_view_top_3_articles_Levis,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_Lee    = Q.Wechat_Avg_view_top_3_articles_Lee,
        SF.Prev_Year_Wechat_Avg_view_top_3_articles_Gap    = Q.Wechat_Avg_view_top_3_articles_Gap,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_Uniqlo = Q.Wechat_Avg_like_top_3_articles_Uniqlo,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_HM     = Q.Wechat_Avg_like_top_3_articles_HM,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_Zara   = Q.Wechat_Avg_like_top_3_articles_Zara,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_Levis  = Q.Wechat_Avg_like_top_3_articles_Levis,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_Lee    = Q.Wechat_Avg_like_top_3_articles_Lee,
        SF.Prev_Year_Wechat_Avg_like_top_3_articles_Gap    = Q.Wechat_Avg_like_top_3_articles_Gap,
        SF.Prev_Year_Weibo_Followers_Growth_Uniqlo         = Q.Weibo_Followers_Growth_Uniqlo,
        SF.Prev_Year_Weibo_Followers_Growth_HM             = Q.Weibo_Followers_Growth_HM,
        SF.Prev_Year_Weibo_Followers_Growth_Zara           = Q.Weibo_Followers_Growth_Zara,
        SF.Prev_Year_Weibo_Followers_Growth_Levis          = Q.Weibo_Followers_Growth_Levis,
        SF.Prev_Year_Weibo_Followers_Growth_Lee            = Q.Weibo_Followers_Growth_Lee,
        SF.Prev_Year_Weibo_Followers_Growth_Gap            = Q.Weibo_Followers_Growth_Gap,
        SF.Prev_Year_Weibo_Engagement_Rate_Uniqlo          = Q.Weibo_Engagement_Rate_Uniqlo,
        SF.Prev_Year_Weibo_Engagement_Rate_HM              = Q.Weibo_Engagement_Rate_HM,
        SF.Prev_Year_Weibo_Engagement_Rate_Zara            = Q.Weibo_Engagement_Rate_Zara,
        SF.Prev_Year_Weibo_Engagement_Rate_Levis           = Q.Weibo_Engagement_Rate_Levis,
        SF.Prev_Year_Weibo_Engagement_Rate_Lee             = Q.Weibo_Engagement_Rate_Lee,
        SF.Prev_Year_Weibo_Engagement_Rate_Gap             = Q.Weibo_Engagement_Rate_Gap
    WHERE SF.Year_Month_Num = Q.P_Year_Month_Num
      AND SF.Country = Q.Country;

    COMMIT;
    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 40, CURRENT_TIMESTAMP());


    Truncate table Fact_DB_Social_China;
    Insert into Fact_DB_Social_China Select * from Stg_Fact_DB_Social_China where Country = 'China';

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 50, CURRENT_TIMESTAMP());

    TRUNCATE TABLE Stg_Fact_DB_Social_China1;

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'Uniqlo' Brand_Name,
           Weibo_Followers_Uniqlo,
           Prev_Weibo_Followers_Uniqlo,
           Prev_Year_Weibo_Followers_Uniqlo,
           Weibo_Tweet_Uniqlo,
           Prev_Weibo_Tweet_Uniqlo,
           Prev_Year_Weibo_Tweet_Uniqlo,
           Weibo_Retweet_Uniqlo,
           Prev_Weibo_Retweet_Uniqlo,
           Prev_Year_Weibo_Retweet_Uniqlo,
           Weibo_Comment_Uniqlo,
           Prev_Weibo_Comment_Uniqlo,
           Prev_Year_Weibo_Comment_Uniqlo,
           Weibo_Likes_Uniqlo,
           Prev_Weibo_Likes_Uniqlo,
           Prev_Year_Weibo_Likes_Uniqlo,
           Weibo_Buzz_Uniqlo,
           Prev_Weibo_Buzz_Uniqlo,
           Prev_Year_Weibo_Buzz_Uniqlo,
           Weibo_Sentiment_Uniqlo,
           Prev_Weibo_Sentiment_Uniqlo,
           Prev_Year_Weibo_Sentiment_Uniqlo,
           Wechat_Avg_view_top_3_articles_Uniqlo,
           Prev_Wechat_Avg_view_top_3_articles_Uniqlo,
           Prev_Year_Wechat_Avg_view_top_3_articles_Uniqlo,
           Wechat_Avg_like_top_3_articles_Uniqlo,
           Prev_Wechat_Avg_like_top_3_articles_Uniqlo,
           Prev_Year_Wechat_Avg_like_top_3_articles_Uniqlo,
           Weibo_Followers_Growth_Uniqlo,
           Prev_Weibo_Followers_Growth_Uniqlo,
           Prev_Year_Weibo_Followers_Growth_Uniqlo,
           Weibo_Engagement_Rate_Uniqlo,
           Prev_Weibo_Engagement_Rate_Uniqlo,
           Prev_Year_Weibo_Engagement_Rate_Uniqlo
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 60, CURRENT_TIMESTAMP());

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'H&M' Brand_Name,
           Weibo_Followers_HM,
           Prev_Weibo_Followers_HM,
           Prev_Year_Weibo_Followers_HM,
           Weibo_Tweet_HM,
           Prev_Weibo_Tweet_HM,
           Prev_Year_Weibo_Tweet_HM,
           Weibo_Retweet_HM,
           Prev_Weibo_Retweet_HM,
           Prev_Year_Weibo_Retweet_HM,
           Weibo_Comment_HM,
           Prev_Weibo_Comment_HM,
           Prev_Year_Weibo_Comment_HM,
           Weibo_Likes_HM,
           Prev_Weibo_Likes_HM,
           Prev_Year_Weibo_Likes_HM,
           Weibo_Buzz_HM,
           Prev_Weibo_Buzz_HM,
           Prev_Year_Weibo_Buzz_HM,
           Weibo_Sentiment_HM,
           Prev_Weibo_Sentiment_HM,
           Prev_Year_Weibo_Sentiment_HM,
           Wechat_Avg_view_top_3_articles_HM,
           Prev_Wechat_Avg_view_top_3_articles_HM,
           Prev_Year_Wechat_Avg_view_top_3_articles_HM,
           Wechat_Avg_like_top_3_articles_HM,
           Prev_Wechat_Avg_like_top_3_articles_HM,
           Prev_Year_Wechat_Avg_like_top_3_articles_HM,
           Weibo_Followers_Growth_HM,
           Prev_Weibo_Followers_Growth_HM,
           Prev_Year_Weibo_Followers_Growth_HM,
           Weibo_Engagement_Rate_HM,
           Prev_Weibo_Engagement_Rate_HM,
           Prev_Year_Weibo_Engagement_Rate_HM
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 70, CURRENT_TIMESTAMP());

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'Zara' Brand_Name,
           Weibo_Followers_Zara,
           Prev_Weibo_Followers_Zara,
           Prev_Year_Weibo_Followers_Zara,
           Weibo_Tweet_Zara,
           Prev_Weibo_Tweet_Zara,
           Prev_Year_Weibo_Tweet_Zara,
           Weibo_Retweet_Zara,
           Prev_Weibo_Retweet_Zara,
           Prev_Year_Weibo_Retweet_Zara,
           Weibo_Comment_Zara,
           Prev_Weibo_Comment_Zara,
           Prev_Year_Weibo_Comment_Zara,
           Weibo_Likes_Zara,
           Prev_Weibo_Likes_Zara,
           Prev_Year_Weibo_Likes_Zara,
           Weibo_Buzz_Zara,
           Prev_Weibo_Buzz_Zara,
           Prev_Year_Weibo_Buzz_Zara,
           Weibo_Sentiment_Zara,
           Prev_Weibo_Sentiment_Zara,
           Prev_Year_Weibo_Sentiment_Zara,
           Wechat_Avg_view_top_3_articles_Zara,
           Prev_Wechat_Avg_view_top_3_articles_Zara,
           Prev_Year_Wechat_Avg_view_top_3_articles_Zara,
           Wechat_Avg_like_top_3_articles_Zara,
           Prev_Wechat_Avg_like_top_3_articles_Zara,
           Prev_Year_Wechat_Avg_like_top_3_articles_Zara,
           Weibo_Followers_Growth_Zara,
           Prev_Weibo_Followers_Growth_Zara,
           Prev_Year_Weibo_Followers_Growth_Zara,
           Weibo_Engagement_Rate_Zara,
           Prev_Weibo_Engagement_Rate_Zara,
           Prev_Year_Weibo_Engagement_Rate_Zara
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 80, CURRENT_TIMESTAMP());

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'Levi''s' Brand_Name,
           Weibo_Followers_Levis,
           Prev_Weibo_Followers_Levis,
           Prev_Year_Weibo_Followers_Levis,
           Weibo_Tweet_Levis,
           Prev_Weibo_Tweet_Levis,
           Prev_Year_Weibo_Tweet_Levis,
           Weibo_Retweet_Levis,
           Prev_Weibo_Retweet_Levis,
           Prev_Year_Weibo_Retweet_Levis,
           Weibo_Comment_Levis,
           Prev_Weibo_Comment_Levis,
           Prev_Year_Weibo_Comment_Levis,
           Weibo_Likes_Levis,
           Prev_Weibo_Likes_Levis,
           Prev_Year_Weibo_Likes_Levis,
           Weibo_Buzz_Levis,
           Prev_Weibo_Buzz_Levis,
           Prev_Year_Weibo_Buzz_Levis,
           Weibo_Sentiment_Levis,
           Prev_Weibo_Sentiment_Levis,
           Prev_Year_Weibo_Sentiment_Levis,
           Wechat_Avg_view_top_3_articles_Levis,
           Prev_Wechat_Avg_view_top_3_articles_Levis,
           Prev_Year_Wechat_Avg_view_top_3_articles_Levis,
           Wechat_Avg_like_top_3_articles_Levis,
           Prev_Wechat_Avg_like_top_3_articles_Levis,
           Prev_Year_Wechat_Avg_like_top_3_articles_Levis,
           Weibo_Followers_Growth_Levis,
           Prev_Weibo_Followers_Growth_Levis,
           Prev_Year_Weibo_Followers_Growth_Levis,
           Weibo_Engagement_Rate_Levis,
           Prev_Weibo_Engagement_Rate_Levis,
           Prev_Year_Weibo_Engagement_Rate_Levis
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 90, CURRENT_TIMESTAMP());

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'Lee' Brand_Name,
           Weibo_Followers_Lee,
           Prev_Weibo_Followers_Lee,
           Prev_Year_Weibo_Followers_Lee,
           Weibo_Tweet_Lee,
           Prev_Weibo_Tweet_Lee,
           Prev_Year_Weibo_Tweet_Lee,
           Weibo_Retweet_Lee,
           Prev_Weibo_Retweet_Lee,
           Prev_Year_Weibo_Retweet_Lee,
           Weibo_Comment_Lee,
           Prev_Weibo_Comment_Lee,
           Prev_Year_Weibo_Comment_Lee,
           Weibo_Likes_Lee,
           Prev_Weibo_Likes_Lee,
           Prev_Year_Weibo_Likes_Lee,
           Weibo_Buzz_Lee,
           Prev_Weibo_Buzz_Lee,
           Prev_Year_Weibo_Buzz_Lee,
           Weibo_Sentiment_Lee,
           Prev_Weibo_Sentiment_Lee,
           Prev_Year_Weibo_Sentiment_Lee,
           Wechat_Avg_view_top_3_articles_Lee,
           Prev_Wechat_Avg_view_top_3_articles_Lee,
           Prev_Year_Wechat_Avg_view_top_3_articles_Lee,
           Wechat_Avg_like_top_3_articles_Lee,
           Prev_Wechat_Avg_like_top_3_articles_Lee,
           Prev_Year_Wechat_Avg_like_top_3_articles_Lee,
           Weibo_Followers_Growth_Lee,
           Prev_Weibo_Followers_Growth_Lee,
           Prev_Year_Weibo_Followers_Growth_Lee,
           Weibo_Engagement_Rate_Lee,
           Prev_Weibo_Engagement_Rate_Lee,
           Prev_Year_Weibo_Engagement_Rate_Lee
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 100, CURRENT_TIMESTAMP());

    INSERT INTO Stg_Fact_DB_Social_China1(Region, Country, Fiscal_Quarter, Fiscal_Year, Year_Month_Num, Fiscal_Month,
                                          Social_Month, Competitor, Weibo_Followers, Prev_Weibo_Followers,
                                          Prev_Year_Weibo_Followers, Weibo_Tweet, Prev_Weibo_Tweet,
                                          Prev_Year_Weibo_Tweet, Weibo_Retweet, Prev_Weibo_Retweet,
                                          Prev_Year_Weibo_Retweet, Weibo_Comment, Prev_Weibo_Comment,
                                          Prev_Year_Weibo_Comment, Weibo_Likes, Prev_Weibo_Likes, Prev_Year_Weibo_Likes,
                                          Weibo_Buzz, Prev_Weibo_Buzz, Prev_Year_Weibo_Buzz, Weibo_Sentiment,
                                          Prev_Weibo_Sentiment,
                                          Prev_Year_Weibo_Sentiment, Wechat_Avg_view_top_3_articles,
                                          Prev_Wechat_Avg_view_top_3_articles, Prev_Year_Wechat_Avg_view_top_3_articles,
                                          Wechat_Avg_like_top_3_articles,
                                          Prev_Wechat_Avg_like_top_3_articles, Prev_Year_Wechat_Avg_like_top_3_articles,
                                          Weibo_Followers_Growth, Prev_Weibo_Followers_Growth,
                                          Prev_Year_Weibo_Followers_Growth,
                                          Weibo_Engagement_Rate, Prev_Weibo_Engagement_Rate,
                                          Prev_Year_Weibo_Engagement_Rate)
    SELECT Region,
           Country,
           Fiscal_Quarter,
           Fiscal_Year,
           Year_Month_Num,
           Fiscal_Month,
           Social_Month,
           'GAP' Brand_Name,
           Weibo_Followers_Gap,
           Prev_Weibo_Followers_Gap,
           Prev_Year_Weibo_Followers_Gap,
           Weibo_Tweet_Gap,
           Prev_Weibo_Tweet_Gap,
           Prev_Year_Weibo_Tweet_Gap,
           Weibo_Retweet_Gap,
           Prev_Weibo_Retweet_Gap,
           Prev_Year_Weibo_Retweet_Gap,
           Weibo_Comment_Gap,
           Prev_Weibo_Comment_Gap,
           Prev_Year_Weibo_Comment_Gap,
           Weibo_Likes_Gap,
           Prev_Weibo_Likes_Gap,
           Prev_Year_Weibo_Likes_Gap,
           Weibo_Buzz_Gap,
           Prev_Weibo_Buzz_Gap,
           Prev_Year_Weibo_Buzz_Gap,
           Weibo_Sentiment_Gap,
           Prev_Weibo_Sentiment_Gap,
           Prev_Year_Weibo_Sentiment_Gap,
           Wechat_Avg_view_top_3_articles_Gap,
           Prev_Wechat_Avg_view_top_3_articles_Gap,
           Prev_Year_Wechat_Avg_view_top_3_articles_Gap,
           Wechat_Avg_like_top_3_articles_Gap,
           Prev_Wechat_Avg_like_top_3_articles_Gap,
           Prev_Year_Wechat_Avg_like_top_3_articles_Gap,
           Weibo_Followers_Growth_Gap,
           Prev_Weibo_Followers_Growth_Gap,
           Prev_Year_Weibo_Followers_Growth_Gap,
           Weibo_Engagement_Rate_Gap,
           Prev_Weibo_Engagement_Rate_Gap,
           Prev_Year_Weibo_Engagement_Rate_Gap
    FROM Fact_DB_Social_China;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 110, CURRENT_TIMESTAMP());


    UPDATE Stg_Fact_DB_Social_China1
    SET Fiscal_Date =
            CONCAT(SUBSTRING(STR_TO_DATE(Year_Month_Num, '%Y%m'), 1, 7), '-01');

    UPDATE Stg_Fact_DB_Social_China1 SF, WeChat_Followers WF
    SET SF.WeChat_Followers        = WF.WeChat_Followers,
        SF.WeChat_Followers_Growth = WF.WeChat_Follwers_Growth
    WHERE SF.Year_Month_Num = WF.Year_Month_Num
      AND SF.Competitor = 'Levi''s';

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 120, CURRENT_TIMESTAMP());

    UPDATE Stg_Fact_DB_Social_China1 SF,
        (SELECT Year_Month_Num + 100 P_Year_Month_Num,
                Competitor,
                Weibo_Sentiment,
                Prev_Year_Weibo_Sentiment,
                Weibo_Engagement_Rate,
                Prev_Year_Weibo_Engagement_Rate,
                WeChat_Followers,
                WeChat_Followers_Growth
         FROM Stg_Fact_DB_Social_China1) Q
    SET SF.Prev_Year_Weibo_Sentiment         = Q.Weibo_Sentiment,
        SF.Prev_Year_Weibo_Engagement_Rate   = Q.Weibo_Engagement_Rate,
        SF.Prev_Year_WeChat_Followers        = Q.WeChat_Followers,
        SF.Prev_Year_WeChat_Followers_Growth = Q.WeChat_Followers_Growth
    WHERE SF.Year_Month_Num = Q.P_Year_Month_Num
      AND SF.Competitor = Q.Competitor;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 130, CURRENT_TIMESTAMP());

    UPDATE Stg_Fact_DB_Social_China1 SF,
        (SELECT CASE
                    WHEN SUBSTR(Year_Month_Num, 5, 2) = '12' THEN Year_Month_Num + 89
                    ELSE Year_Month_Num + 1 END P_Year_Month_Num,
                Competitor,
                Weibo_Sentiment,
                Prev_Weibo_Sentiment,
                Weibo_Engagement_Rate,
                Prev_Weibo_Engagement_Rate,
                WeChat_Followers,
                WeChat_Followers_Growth
         FROM Stg_Fact_DB_Social_China1) Q
    SET SF.Prev_Weibo_Sentiment         = Q.Weibo_Sentiment,
        SF.Prev_Weibo_Engagement_Rate   = Q.Weibo_Engagement_Rate,
        SF.Prev_WeChat_Followers        = Q.WeChat_Followers,
        SF.Prev_WeChat_Followers_Growth = Q.WeChat_Followers_Growth
    WHERE SF.Year_Month_Num = Q.P_Year_Month_Num
      AND SF.Competitor = Q.Competitor;
/*
This value will be given by Neha every month
update Stg_Fact_DB_Social_China1 
SET WeChat_Followers =  880973,
WeChat_Followers_Growth = 0.056
where Year_Month_Num =201901 and Competitor ='Levi''s';
*/
    TRUNCATE TABLE Fact_DB_Social_China1;
    INSERT INTO Fact_DB_Social_China1 SELECT * FROM Stg_Fact_DB_Social_China1;

    INSERT INTO Job_Info_Dtls
    VALUES (i_Job_ID, 'Pop_Fact_DB_Social_China', NULL, 140, CURRENT_TIMESTAMP());

END;


