create definer = gilbert@`%` view DB_Social_Media_China_View as
select `FDC`.`Region`                                                           AS `Region`,
       `FDC`.`Country`                                                          AS `Country`,
       `FDC`.`Fiscal_Quarter`                                                   AS `Fiscal_Quarter`,
       `FDC`.`Fiscal_Year`                                                      AS `Fiscal_Year_Num`,
       concat(`FDC`.`Fiscal_Month`, '-', substr(`FDC`.`Year_Month_Num`, 3, 2))  AS `Year_Month_Char`,
       case when `FDC`.`Fiscal_Quarter` in ('Q1', 'Q2') then 'H1' else 'H2' end AS `Fiscal_Biannual`,
       `CURR_FISCAL_YEAR`()                                                     AS `Curr_Fiscal_Year`,
       `FDC`.`Year_Month_Num`                                                   AS `Fiscal_Month_Num`,
       `FDC`.`Fiscal_Month`                                                     AS `Fiscal_Month`,
       `FDC`.`Social_Month`                                                     AS `Social_Month`,
       `FDC`.`Fiscal_Date`                                                      AS `Fiscal_Date`,
       `FDC`.`Competitor`                                                       AS `Competitor`,
       `FDC`.`Weibo_Followers`                                                  AS `Weibo_Followers`,
       `FDC`.`Prev_Weibo_Followers`                                             AS `Prev_Weibo_Followers`,
       `FDC`.`Prev_Year_Weibo_Followers`                                        AS `Prev_Year_Weibo_Followers`,
       `FDC`.`Weibo_Tweet`                                                      AS `Weibo_Tweet`,
       `FDC`.`Prev_Weibo_Tweet`                                                 AS `Prev_Weibo_Tweet`,
       `FDC`.`Prev_Year_Weibo_Tweet`                                            AS `Prev_Year_Weibo_Tweet`,
       `FDC`.`Weibo_Retweet`                                                    AS `Weibo_Retweet`,
       `FDC`.`Prev_Weibo_Retweet`                                               AS `Prev_Weibo_Retweet`,
       `FDC`.`Prev_Year_Weibo_Retweet`                                          AS `Prev_Year_Weibo_Retweet`,
       `FDC`.`Weibo_Comment`                                                    AS `Weibo_Comment`,
       `FDC`.`Prev_Weibo_Comment`                                               AS `Prev_Weibo_Comment`,
       `FDC`.`Prev_Year_Weibo_Comment`                                          AS `Prev_Year_Weibo_Comment`,
       `FDC`.`Weibo_Likes`                                                      AS `Weibo_Likes`,
       `FDC`.`Prev_Weibo_Likes`                                                 AS `Prev_Weibo_Likes`,
       `FDC`.`Prev_Year_Weibo_Likes`                                            AS `Prev_Year_Weibo_Likes`,
       `FDC`.`Weibo_Buzz`                                                       AS `Weibo_Buzz`,
       `FDC`.`Prev_Weibo_Buzz`                                                  AS `Prev_Weibo_Buzz`,
       `FDC`.`Prev_Year_Weibo_Buzz`                                             AS `Prev_Year_Weibo_Buzz`,
       `FDC`.`Weibo_Sentiment`                                                  AS `Weibo_Sentiment`,
       `FDC`.`Prev_Weibo_Sentiment`                                             AS `Prev_Weibo_Sentiment`,
       `FDC`.`Prev_Year_Weibo_Sentiment`                                        AS `Prev_Year_Weibo_Sentiment`,
       `FDC`.`Wechat_Avg_view_top_3_articles`                                   AS `Wechat_Avg_view_top_3_articles`,
       `FDC`.`Prev_Wechat_Avg_view_top_3_articles`                              AS `Prev_Wechat_Avg_view_top_3_articles`,
       `FDC`.`Prev_Year_Wechat_Avg_view_top_3_articles`                         AS `Prev_Year_Wechat_Avg_view_top_3_articles`,
       `FDC`.`Wechat_Avg_like_top_3_articles`                                   AS `Wechat_Avg_like_top_3_articles`,
       `FDC`.`Prev_Wechat_Avg_like_top_3_articles`                              AS `Prev_Wechat_Avg_like_top_3_articles`,
       `FDC`.`Prev_Year_Wechat_Avg_like_top_3_articles`                         AS `Prev_Year_Wechat_Avg_like_top_3_articles`,
       `FDC`.`Weibo_Followers_Growth`                                           AS `Weibo_Followers_Growth`,
       `FDC`.`Prev_Weibo_Followers_Growth`                                      AS `Prev_Weibo_Followers_Growth`,
       `FDC`.`Prev_Year_Weibo_Followers_Growth`                                 AS `Prev_Year_Weibo_Followers_Growth`,
       `FDC`.`Weibo_Engagement_Rate`                                            AS `Weibo_Engagement_Rate`,
       `FDC`.`Prev_Weibo_Engagement_Rate`                                       AS `Prev_Weibo_Engagement_Rate`,
       `FDC`.`Prev_Year_Weibo_Engagement_Rate`                                  AS `Prev_Year_Weibo_Engagement_Rate`,
       `FDC`.`WeChat_Followers`                                                 AS `WeChat_Followers`,
       `FDC`.`Prev_WeChat_Followers`                                            AS `Prev_WeChat_Followers`,
       `FDC`.`Prev_Year_WeChat_Followers`                                       AS `Prev_Year_WeChat_Followers`,
       `FDC`.`WeChat_Followers_Growth`                                          AS `WeChat_Followers_Growth`,
       `FDC`.`Prev_WeChat_Followers_Growth`                                     AS `Prev_WeChat_Followers_Growth`,
       `FDC`.`Prev_Year_WeChat_Followers_Growth`                                AS `Prev_Year_WeChat_Followers_Growth`
from `LEVIS_MET2`.`Fact_DB_Social_China1` `FDC`;


